<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>img\Maple.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.37.2" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="img\AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Servers\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
